from enum import Enum


class ErrorCodes(str, Enum):
    INVALID_INPUT = "INVALID_INPUT"
    NOT_FOUND = "NOT_FOUND"
    AUTH_REQUIRED = "AUTH_REQUIRED"
    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"
    UNSUPPORTED_FEATURE = "UNSUPPORTED_FEATURE"
    TELEGRAM_API_ERROR = "TELEGRAM_API_ERROR"
    INTERNAL_ERROR = "INTERNAL_ERROR"
